@module("node:path") external join2: (string, string) => string = "join"
@module("node:path") external join3: (string, string, string) => string = "join"
@module("node:path") external join4: (string, string, string, string) => string = "join"
@module("node:path") external dirname: string => string = "dirname"
@module("node:path") external basename: string => string = "basename"
@module("node:path") external extname: string => string = "extname"
@module("node:path") external relative: (string, string) => string = "relative"
@module("node:path") external resolve1: string => string = "resolve"
@module("node:path") external resolve2: (string, string) => string = "resolve"
@module("node:path") external sep: string = "sep"
